const assert = require('node:assert/strict');
const flow = require('./processFlowCore');
let checks = 0;
const check = (v, name) => { assert(v, name); checks++; console.log('PASS '+name); };
const rows = Array.from({length:8}, (_,i)=>({id:`p${i+1}`,process_order:i+1,process_name:`測試工序${i+1}`,process_type:'cnc',machine_code:'A01',status:i===0?'completed':i===1?'running':'pending',reported:i===0?100:i===1?48:0}));
rows[4] = {...rows[4],process_type:'outsourced',supplier_code:'TEST-VENDOR'};
check(flow.steps(rows,'p2').length===8,'eight real steps retained');
check(flow.steps(rows,'p2').filter(p=>p.current).length===1,'current comes from exact process identity');
check(flow.steps(rows).filter(p=>p.current).length===1,'unique running step may identify current in management');
check(flow.steps([{id:'a',status:'running'},{id:'b',status:'running'}]).every(p=>!p.current),'ambiguous running steps do not guess current');
check(flow.steps(rows).at(0).label==='已完成','completed step');
check(flow.steps(rows)[1].label==='進行中','running step');
check(flow.steps(rows)[4].label==='待發包','pending outsourced step');
check(flow.steps([{...rows[4],status:'running'}])[0].label==='委外中','running outsourced step');
check(flow.steps([{id:'gap',process_order:7,PP_Name:'原製程',status:'paused'}])[0].name==='原製程','blank name falls back to source route');
check(flow.steps([{process_order:7}]).length===1,'missing earlier steps never invented');
check(flow.steps([{status:'paused'}])[0].label==='狀態待確認','paused is not mislabeled as running');
check(flow.render([{process_order:3,process_name:'<img onerror=x>',reported:null}],{quantity:0}).includes('&lt;img'),'source names escaped');
check(flow.render([{process_order:3,reported:null}],{quantity:0}).includes('已報無資料 / 0'),'unknown output not displayed as zero');
check(flow.render(rows,{currentId:'p2',quantity:100}).includes('aria-current="step"'),'accessible current marker');
check(flow.render(rows).includes('TEST-VENDOR'),'vendor code retained');
check(!flow.render(rows).includes('<button')&&!flow.render(rows).includes('<form'),'display component cannot mutate');
check(flow.render([]).includes('無資料'),'empty route explicit');
const latheRows=rows.map(p=>({...p,process_name:'CNC車床加工'}));
const machines=[{id:'a',code:'A01',department:'車床課',status:'idle'},
 {id:'bad',code:'A02',department:'車床課',status:'maintenance'},
 {id:'mill',code:'B01',department:'銑床課',status:'idle'}];
check(flow.preplanTarget(latheRows,'p2')?.id==='p3','only immediate next existing step can be preplanned');
check(flow.candidateMachines(flow.preplanTarget(latheRows,'p2'),machines).map(x=>x.id).join()==='a','same department only, maintenance excluded');
check(flow.preplanTarget(latheRows.map(p=>p.id==='p3'?{...p,hasReports:true}:p),'p2')===null,'reported next step not editable');
check(flow.preplanTarget(latheRows.map(p=>p.id==='p3'?{...p,reported:null}:p),'p2')===null,'failed progress source disables preplan');
check(flow.preplanTarget(latheRows.map(p=>p.id==='p3'?{...p,process_type:'outsourced'}:p),'p2')===null,'outsourced next step not assignable');
check(!flow.render(latheRows,{currentId:'p2',canPreplan:true,machines}).includes('data-flow-append'),'missing audit migration fails closed');
check(flow.render(latheRows,{currentId:'p2',canPreplan:true,machines,auditAvailable:true}).includes('data-flow-append="p3"'),'authorized preplan control on next step');
check(flow.render([{...rows[0],assignmentEvent:{kind:'legacy_reassigned'}}]).includes('已依舊 MES 改派'),'only recorded legacy reassignment shown');
const fallbackRows=latheRows.map(p=>p.id==='p3'?{...p,process_name:'精修',machine_department:'車床課'}:p);
check(flow.preplanTarget(fallbackRows,'p2')?.id==='p3','unknown operation name uses existing assigned machine department');
check(flow.candidateMachines(flow.preplanTarget(fallbackRows,'p2'),machines).map(x=>x.id).join()==='a','fallback does not permit another department');
check(flow.preplanTarget(fallbackRows.map(p=>p.id==='p3'?{...p,machine_department:null}:p),'p2')===null,'unknown and unassigned operation cannot infer from destination');
check(flow.candidateMachines({name:'車削'},[{id:'null-dept',type:'lathe',department:null,status:'idle'}]).length===0,'machine type never substitutes for missing department');
const preview=flow.render(rows,{currentId:'p2',quantity:100,compact:true,orderNo:'TEST-ORDER'});
check((preview.match(/class="process-flow-step /g)||[]).length===3,'compact preview has only previous/current/next');
check(preview.includes('上一道 ✓')&&preview.includes('目前道')&&preview.includes('下一道'),'previous completion tick uses actual completed status');
check(preview.includes('共 8 道')&&preview.includes('data-flow-open="TEST-ORDER"'),'compact preview exposes complete-route entry and real count');
check(!preview.includes('data-flow-process="p8"'),'downstream route not crowded into card');
check(!flow.render(rows,{currentId:'p2',compact:true,canPreplan:true,auditAvailable:true,machines}).includes('data-flow-append'),'compact opener has no nested mutation controls');
check((flow.render(rows,{currentId:'p1',compact:true}).match(/class="process-flow-step /g)||[]).length===2,'first step never fabricates previous step');
check((flow.render(rows,{currentId:'p8',compact:true}).match(/class="process-flow-step /g)||[]).length===2,'last step never fabricates next step');
check(flow.render(rows.map(p=>({...p,status:'pending'})),{compact:true}).includes('目前道未確認'),'unknown current does not guess a preview');
check(flow.render(rows,{currentId:'p2',alignCurrent:false}).includes('data-flow-aligned="true"'),'full route may start at N1 instead of auto-scrolling current');
// Part A: pending status follows the SAME reported quantity the card shows (legacy MES + App via cardProgress).
const qtyRow=(reported,status='pending')=>flow.steps([{id:'q',process_order:3,process_name:'CNC車床加工',machine_code:'A01',status,reported,qty_completed:0}],null,5000)[0].label;
check(qtyRow(0)==='未開始','pending with reported 0 => 未開始');
check(qtyRow(4690)==='進行中','legacy-reported 4690/5000 with no App report (qty_completed 0) => 進行中, not 未開始 (XX01202609020008 N3 A01)');
check(qtyRow(5000)==='已達數'&&qtyRow(5200)==='已達數'&&!flow.render([{id:'q',process_order:3,status:'pending',reported:5000}],{quantity:5000}).includes('完成'),'reported >= quantity => 已達數, never 完成');
check(qtyRow(4690,'running')==='進行中'&&qtyRow(0,'completed')==='已完成'&&qtyRow(4690,'paused')==='狀態待確認'&&qtyRow(5000,'abnormal')==='狀態待確認'&&qtyRow(10,'waiting_inspection')==='狀態待確認','explicit statuses keep existing labels and take precedence over quantity');
check(qtyRow(null)==='未開始'&&flow.render([{id:'q',process_order:3,status:'pending',reported:null}],{quantity:5000}).includes('已報無資料'),'unknown progress is not shown as zero output');
check(flow.steps([{id:'q',status:'pending',reported:30}],null,null)[0].label==='進行中','unknown work-order quantity never claims 已達數');
check(flow.steps([{id:'q',status:'pending',process_type:'outsourced',reported:30}],null,100)[0].label==='待發包','outsourced pending keeps its own label');
// Part B: per-role visibility levels. Default for every role is full.
check(Object.values(flow.normalizeVisibility(null)).every(v=>v==='full')&&flow.ROLES.length===6,'every role defaults to full');
check(flow.visibilityLevel({operator:'bogus'},'operator')==='full'&&flow.visibilityLevel({operator:'hidden'},'unknown-role')==='full','invalid level or unknown role falls back to full');
const lv=(visibility,extra={})=>flow.render(rows,{currentId:'p2',quantity:100,compact:true,orderNo:'TEST-ORDER',visibility,...extra});
check(lv('full')===preview&&lv(undefined)===preview,'full level is exactly today preview (opener included)');
check((lv('adjacent').match(/class="process-flow-step /g)||[]).length===3&&!lv('adjacent').includes('data-flow-open')&&!lv('adjacent').includes('點開看完整路線')&&!lv('adjacent').includes('共 8 道'),'adjacent shows three cells without full-route expansion');
check(!flow.render(rows,{currentId:'p2',quantity:100,compact:false,visibility:'adjacent'}).includes('data-flow-process="p8"'),'adjacent never renders full route even when asked for non-compact');
const nextOnly=lv('next_only',{nextQueued:{status:'ok',orderNo:'NEXT-ORDER',operation:'N2 車削',part:'零件'}});
check(nextOnly.includes('data-flow-process="p3"')&&!nextOnly.includes('data-flow-process="p2"')&&!nextOnly.includes('data-flow-process="p1"')&&!nextOnly.includes('data-flow-process="p4"'),'next_only shows only this order next step');
check(nextOnly.includes('本機下一張')&&nextOnly.includes('NEXT-ORDER')&&!nextOnly.includes('data-flow-open')&&!nextOnly.includes('共 8 道'),'next_only shows machine next queued order and no route opener/count');
check(lv('next_only',{nextQueued:{status:'none'}}).includes('本機佇列沒有下一張')&&lv('next_only').includes('佇列資料無法確認'),'next_only queue empty vs unknown are distinct');
check(flow.render(rows,{currentId:'p8',compact:true,visibility:'next_only',nextQueued:{status:'none'}}).includes('最後一道'),'next_only last step never invents a next step');
check(lv('hidden')===''&&flow.render([],{visibility:'hidden'})==='','hidden renders no flow strip');
const metadata=Array.from({length:8},(_,i)=>({step_no:i+1,operation_name:`BOM-${i+1}`,is_outsourced:i===0||i===3,supplier_name:i===0?'測試廠商':'',supplier_no:i===0?'TEST-V':'',station_no:'TEST'}));
const actual=[{...rows[1],process_name:'old',process_order:2,reported:48},{...rows[2],process_order:3,reported:100,status:'completed'}];
const merged=flow.mergeRoute(metadata,actual,'TEST-ORDER');
check(merged.length===8&&merged[0].routeOnly,'all BOM steps retained without dispatch rows');
check(merged[1].id===actual[0].id&&merged[1].reported===48&&merged[1].process_name==='BOM-2','actual ID/progress retained, operation name from BOM');
check(flow.steps(merged,actual[0].id,100)[2].label==='已完成','actual completed status preserved');
check(flow.steps(merged)[0].resource==='委外：測試廠商'&&flow.steps(merged)[0].label==='委外狀態無資料','display-only outsource has vendor but no invented status');
check(!flow.render(merged,{currentId:actual[0].id,canPreplan:true,auditAvailable:true,machines}).includes('data-flow-append'),'outsource or missing actual process cannot be preplanned');
check(flow.mergeRoute([],actual,'TEST-ORDER').length===2,'missing route retains old processes');
check(flow.steps(merged)[7].resource==='機台無資料'&&flow.steps(merged)[7].done===null,'unassigned metadata does not invent assignment/zero output');
check(flow.render(merged,{visibility:'hidden'})==='','merged route respects hidden');
check(!flow.render(merged,{currentId:actual[0].id,visibility:'next_only'}).includes('data-flow-process="route:TEST-ORDER:8"'),'merged route respects next_only');
assert.throws(()=>flow.mergeRoute([metadata[0],metadata[0]],actual,'TEST'),/invalid display route/);check(true,'duplicate route fails instead of guessing');
assert.throws(()=>flow.mergeRoute([{...metadata[0],work_order_no:'OTHER'}],actual,'TEST'),/invalid display route/);check(true,'different-order route never attaches to this order');
console.log(`${checks}/${checks} PASS`);
